"""CSS codes to build Shor-style syndrome extraction gadgets for.

Each code carries its X- and Z-type parity checks as binary matrices; a row is
one stabilizer generator and its support is the set of data qubits the gadget's
transversal CNOTs touch. Stabilizer weight is what sizes the cat state, so the
library is chosen to span the weights that matter: 2 and 4 (surface, Steane),
6 (Shor), 8 (Hamming, Golay).
"""
from dataclasses import dataclass

import numpy as np


@dataclass
class CSSCode:
    name: str
    hx: np.ndarray   # rows are X-type generators: measure X on the row's support
    hz: np.ndarray   # rows are Z-type generators
    n: int
    k: int
    d: int

    def __post_init__(self):
        # CSS condition: every X generator overlaps every Z generator evenly.
        assert (self.hx @ self.hz.T % 2 == 0).all(), f"{self.name}: checks anticommute"

    def stabilizers(self):
        """[(kind, support)] with kind in {"X", "Z"}, X-type first."""
        out = []
        for kind, h in (("X", self.hx), ("Z", self.hz)):
            for row in h:
                out.append((kind, [int(q) for q in np.flatnonzero(row)]))
        return out

    @property
    def weights(self):
        return sorted({len(s) for _, s in self.stabilizers()})


def _a(rows):
    return np.array(rows, dtype=np.uint8)


# [[7,1,3]] Steane, in the qubit labelling used by low/simulations/utils.H_x so
# these gadgets line up with the existing Steane work in this repo.
_STEANE_H = _a([[1, 1, 1, 1, 0, 0, 0],
                [0, 1, 1, 0, 1, 1, 0],
                [0, 0, 1, 1, 0, 1, 1]])
STEANE = CSSCode("steane", _STEANE_H, _STEANE_H, 7, 1, 3)

# [[9,1,3]] Shor code: weight-2 Z checks inside each triple, weight-6 X checks
# across adjacent triples. The weight-2 checks are the interesting case for a
# Bell-pair reduction -- a 2-qubit "cat state" is literally a Bell pair.
SHOR9 = CSSCode(
    "shor9",
    _a([[1] * 6 + [0] * 3,
        [0] * 3 + [1] * 6]),
    _a([[1 if q in (i, i + 1) else 0 for q in range(9)]
        for i in (0, 1, 3, 4, 6, 7)]),
    9, 1, 3)


def rotated_surface(d: int) -> CSSCode:
    """Rotated surface code on a d x d grid, qubit (r, c) -> r * d + c.

    Bulk plaquettes are weight 4; the boundary carries weight-2 checks, which is
    where a Shor gadget degenerates to a Bell-pair ancilla.
    """
    hx, hz = [], []
    idx = lambda r, c: r * d + c
    for r in range(d - 1):
        for c in range(d - 1):
            # Faces alternate in colour like a checkerboard.
            supp = [idx(r, c), idx(r, c + 1), idx(r + 1, c), idx(r + 1, c + 1)]
            (hz if (r + c) % 2 == 0 else hx).append(supp)
    for c in range(0, d - 1, 2):                      # top / bottom boundary
        hx.append([idx(0, c), idx(0, c + 1)])
    for c in range(1, d - 1, 2):
        hx.append([idx(d - 1, c), idx(d - 1, c + 1)])
    for r in range(1, d - 1, 2):                      # left / right boundary
        hz.append([idx(r, 0), idx(r + 1, 0)])
    for r in range(0, d - 1, 2):
        hz.append([idx(r, d - 1), idx(r + 1, d - 1)])

    def rows(supports):
        m = np.zeros((len(supports), d * d), dtype=np.uint8)
        for i, s in enumerate(supports):
            m[i, s] = 1
        return m

    return CSSCode(f"surface{d}", rows(hx), rows(hz), d * d, 1, d)


def hamming15() -> CSSCode:
    """[[15,7,3]] from the Hamming(15,11) code: 4 checks of weight 8 per type."""
    h = np.array([[(q >> b) & 1 for q in range(1, 16)] for b in range(4)], dtype=np.uint8)
    return CSSCode("hamming15", h, h, 15, 7, 3)


def golay23() -> CSSCode:
    """[[23,1,7]] quantum Golay code: 11 checks of weight 8 per type.

    C = [23,12,7] binary Golay, stabilizers generated by C^perp = [23,11,8].
    Distance 7 means t = 3, so its weight-8 cat states need the paper's FT_3
    preparation -- the regime the vendored cat circuits actually cover.
    """
    g = [1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1]          # x^11+x^10+x^6+x^5+x^4+x^2+1
    gen = np.zeros((12, 23), dtype=np.uint8)
    for i in range(12):
        gen[i, i:i + len(g)] = g
    # C^perp = null space of the generator matrix of C.
    dual = _nullspace(gen)
    assert dual.shape[0] == 11, dual.shape
    assert set(dual.sum(1)) == {8}, sorted(set(dual.sum(1).tolist()))
    return CSSCode("golay23", dual, dual, 23, 1, 7)


def _nullspace(m: np.ndarray) -> np.ndarray:
    """Basis of {v : m v = 0} over GF(2), rows chosen to be weight-8 codewords
    where possible by reducing the raw basis against itself."""
    a = m.copy() % 2
    rows, cols = a.shape
    pivots, r = [], 0
    for c in range(cols):
        p = next((i for i in range(r, rows) if a[i, c]), None)
        if p is None:
            continue
        a[[r, p]] = a[[p, r]]
        for i in range(rows):
            if i != r and a[i, c]:
                a[i] ^= a[r]
        pivots.append(c)
        r += 1
    free = [c for c in range(cols) if c not in pivots]
    basis = np.zeros((len(free), cols), dtype=np.uint8)
    for j, f in enumerate(free):
        basis[j, f] = 1
        for i, c in enumerate(pivots):
            basis[j, c] = a[i, f]
    return _minimise_weights(basis)


def _minimise_weights(basis: np.ndarray) -> np.ndarray:
    """Greedily reduce each row against the others; for the Golay dual this pulls
    every generator down to its minimum weight 8."""
    b = basis.copy()
    changed = True
    while changed:
        changed = False
        for i in range(len(b)):
            for j in range(len(b)):
                if i != j and (b[i] ^ b[j]).sum() < b[i].sum():
                    b[i] ^= b[j]
                    changed = True
    return b


CODES = {
    "steane": lambda: STEANE,
    "shor9": lambda: SHOR9,
    "surface3": lambda: rotated_surface(3),
    "surface5": lambda: rotated_surface(5),
    "hamming15": hamming15,
    "golay23": golay23,
}


def get(name: str) -> CSSCode:
    if name not in CODES:
        raise KeyError(f"unknown code {name!r}; have {sorted(CODES)}")
    return CODES[name]()
